<h1 align="center"><font size="5">Final Project: Classification with Python</font></h1>

# Instructions


In this notebook, you will  practice all the classification algorithms that we have learned in this course.


Below, is where we are going to use the classification algorithms to create a model based on our training data and evaluate our testing data using evaluation metrics learned in the course.

We will use some of the algorithms taught in the course, specifically:

1. Linear Regression
2. KNN
3. Decision Trees
4. Logistic Regression
5. SVM

We will evaluate our models using:

1.  Accuracy Score
2.  Jaccard Index
3.  F1-Score
4.  LogLoss
5.  Mean Absolute Error
6.  Mean Squared Error
7.  R2-Score

Finally, you will use your models to generate the report at the end.


# About The Dataset


The original source of the data is Australian Government's Bureau of Meteorology and the latest data can be gathered from [http://www.bom.gov.au/climate/dwo/](http://www.bom.gov.au/climate/dwo/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01).

The dataset to be used has extra columns like 'RainToday' and our target is 'RainTomorrow', which was gathered from the Rattle at [https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData](https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)




This dataset contains observations of weather metrics for each day from 2008 to 2017. The **weatherAUS.csv** dataset includes the following fields:

| Field         | Description                                           | Unit            | Type   |
| ------------- | ----------------------------------------------------- | --------------- | ------ |
| Date          | Date of the Observation in YYYY-MM-DD                 | Date            | object |
| Location      | Location of the Observation                           | Location        | object |
| MinTemp       | Minimum temperature                                   | Celsius         | float  |
| MaxTemp       | Maximum temperature                                   | Celsius         | float  |
| Rainfall      | Amount of rainfall                                    | Millimeters     | float  |
| Evaporation   | Amount of evaporation                                 | Millimeters     | float  |
| Sunshine      | Amount of bright sunshine                             | hours           | float  |
| WindGustDir   | Direction of the strongest gust                       | Compass Points  | object |
| WindGustSpeed | Speed of the strongest gust                           | Kilometers/Hour | object |
| WindDir9am    | Wind direction averaged of 10 minutes prior to 9am    | Compass Points  | object |
| WindDir3pm    | Wind direction averaged of 10 minutes prior to 3pm    | Compass Points  | object |
| WindSpeed9am  | Wind speed averaged of 10 minutes prior to 9am        | Kilometers/Hour | float  |
| WindSpeed3pm  | Wind speed averaged of 10 minutes prior to 3pm        | Kilometers/Hour | float  |
| Humidity9am   | Humidity at 9am                                       | Percent         | float  |
| Humidity3pm   | Humidity at 3pm                                       | Percent         | float  |
| Pressure9am   | Atmospheric pressure reduced to mean sea level at 9am | Hectopascal     | float  |
| Pressure3pm   | Atmospheric pressure reduced to mean sea level at 3pm | Hectopascal     | float  |
| Cloud9am      | Fraction of the sky obscured by cloud at 9am          | Eights          | float  |
| Cloud3pm      | Fraction of the sky obscured by cloud at 3pm          | Eights          | float  |
| Temp9am       | Temperature at 9am                                    | Celsius         | float  |
| Temp3pm       | Temperature at 3pm                                    | Celsius         | float  |
| RainToday     | If there was rain today                               | Yes/No          | object |
| RainTomorrow  | If there is rain tomorrow                             | Yes/No          | float  |

Column definitions were gathered from [http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml](http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)



#Importing Required Libraries

Surpress Warnings

In [ ]:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

Importing Libraries

In [ ]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics

#Importing the Dataset

In [ ]:
path='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv'

In [ ]:
df = pd.read_csv(path)
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

In [ ]:
df.dtypes

Date              object
MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed      int64
WindDir9am        object
WindDir3pm        object
WindSpeed9am       int64
WindSpeed3pm       int64
Humidity9am        int64
Humidity3pm        int64
Pressure9am      float64
Pressure3pm      float64
Cloud9am           int64
Cloud3pm           int64
Temp9am          float64
Temp3pm          float64
RainToday         object
RainTomorrow      object
dtype: object

#Data Preprocessing

###One Hot Encoding

First Step, we need First, we need to convert 'RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm' columns from categorical variables to binary variables

In [ ]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])

The next step is we going to convert "No" and "Yes Value to 0 and 1 (Binary Value)

In [ ]:
df_sydney_processed.replace(['No', 'Yes'], [0, 1], inplace=True)

#Splitting the data into train and test set

Setting up our X values and y or target variable.

In [ ]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [ ]:
df_sydney_processed = df_sydney_processed.astype(float)

In [ ]:
X = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
y = df_sydney_processed['RainTomorrow']

#### Q1) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `10`.

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [ ]:
print(f"x_train shape: {x_train.shape}")
print(f"x_test shape: {x_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

x_train shape: (2616, 66)
x_test shape: (655, 66)
y_train shape: (2616,)
y_test shape: (655,)


#Linear Regression

#### Q2) Create and train a Linear Regression model called LinearReg using the training data (`x_train`, `y_train`).

In [ ]:
from sklearn import linear_model
LinearReg = linear_model.LinearRegression()
train_x = np.array(x_train)
train_y = np.array(y_train)
LinearReg.fit(train_x, train_y)

print ('Coefficients: ', LinearReg.coef_)

Coefficients:  [-0.02369173  0.01300554  0.00072981  0.00649077 -0.03516427  0.00423762
  0.0018292   0.00078986  0.00095609  0.00856061  0.00769793 -0.00924424
 -0.00887454  0.01004774  0.01446555 -0.00348065 -0.05402493  0.05402493
  0.05039419 -0.07898527  0.06640003 -0.0721012  -0.05945626 -0.08239011
 -0.0789619   0.06418738 -0.00838878  0.11105128  0.01414852  0.03851666
  0.03625722 -0.02133122  0.00395909  0.01670037  0.04350405  0.05317842
 -0.00692976 -0.01911823 -0.01461142 -0.00594829 -0.07546046  0.04176858
 -0.00758587 -0.00980346 -0.01874997  0.00302978  0.01914623 -0.0012425
 -0.01756641  0.01638932 -0.09330032 -0.08339081 -0.01838672 -0.05191842
 -0.04092463  0.03423083  0.06883841  0.01862747  0.06892422  0.00033817
 -0.04820507  0.0755034   0.03967488  0.02636872 -0.02236214  0.02598199]


#### Q3) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.

In [ ]:
predictions = LinearReg.predict(x_test)

print("Predictions ", predictions)

Predictions  [ 1.31840712e-01  2.76185900e-01  9.78188185e-01  2.87456100e-01
  1.32413708e-01  4.60464181e-01  3.56787457e-01  8.56406853e-01
  6.75011913e-01  3.82473927e-02  4.77419539e-03  2.81216244e-01
  3.39082151e-01  7.80932817e-02  6.25941374e-02  5.64436895e-01
 -6.15522275e-02  5.24162822e-01  1.53690035e-01  3.59699285e-01
  6.05340925e-02  9.03559778e-01  4.67319777e-01  2.03371127e-01
 -7.10231590e-02  3.83879525e-01  5.36083689e-01 -2.28933693e-02
  6.40131507e-01 -9.56732521e-02  3.78086413e-01  1.20264352e-01
 -1.81459863e-02  5.53851712e-02  5.63533571e-01  1.06298389e+00
 -6.75137845e-03  5.14393583e-01 -8.83888189e-02  6.91943913e-02
  2.44741034e-02  8.71740067e-01  2.44667654e-01  3.94725191e-01
  2.67561501e-01  4.46793579e-01 -4.75684922e-02  1.89430640e-01
  7.76606954e-01  1.57760377e-01  3.94719448e-03 -5.19683322e-02
  2.07339163e-01 -2.07888133e-01 -7.61137847e-02  2.49651865e-01
  2.79297446e-01  6.02773116e-01  6.29592460e-01  4.90636291e-01
  5.64565303

#### Q4) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.

In [ ]:
from sklearn.metrics import r2_score

test_x = np.array(x_test)
test_y = np.array(y_test)
test_y_ = LinearReg.predict(test_x)

print("Mean absolute error: %.2f" % np.mean(np.absolute(test_y_ - test_y)))
print("Residual sum of squares (MSE): %.2f" % np.mean((test_y_ - test_y) ** 2))
print("R2-score: %.2f" % r2_score(test_y , test_y_) )

Mean absolute error: 0.26
Residual sum of squares (MSE): 0.12
R2-score: 0.43


#### Q5) Show the MAE, MSE, and R2 in a tabular format using data frame for the linear model.

In [ ]:
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Calculate metrics
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

# Create a DataFrame for the metrics
metrics_df = pd.DataFrame({
    "Metric": ["Mean Absolute Error (MAE)", "Mean Squared Error (MSE)", "R²-score"],
    "Value": [mae, mse, r2]
})

# Display the DataFrame
print(metrics_df)


                      Metric     Value
0  Mean Absolute Error (MAE)  0.256318
1   Mean Squared Error (MSE)  0.115721
2                   R²-score  0.427132


#KNN

#### Q6) Create and train a KNN model called KNN using the training data (`x_train`, `y_train`) with the `n_neighbors` parameter set to `4`.

In [ ]:
KNN = KNeighborsClassifier(n_neighbors = 4).fit(x_train, y_train)

#### Q7) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.

In [ ]:
predicitions = KNN.predict(x_test)
predictions[0:5]

array([0.13184071, 0.2761859 , 0.97818819, 0.2874561 , 0.13241371])

#### Q8) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.

In [ ]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score

predictions_binary = (predictions >= 0.5).astype(int)
KNN_Accuracy_Score = accuracy_score(y_test, predictions_binary)
KNN_JaccardIndex = jaccard_score(y_test, predictions_binary)
KNN_F1_Score = f1_score(y_test, predictions_binary)

print(f"KNN Accuracy Score: {KNN_Accuracy_Score}")
print(f"KNN Jaccard Index: {KNN_JaccardIndex}")
print(f"KNN F1 Score: {KNN_F1_Score}")

KNN Accuracy Score: 0.8366412213740458
KNN Jaccard Index: 0.5136363636363637
KNN F1 Score: 0.6786786786786787


#Decision Tree

#### Q9) Create and train a Decision Tree model called Tree using the training data (`x_train`, `y_train`).

In [ ]:
Tree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
Tree

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [ ]:
Tree.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

#### Q10) Now use the `predict` method on the testing data (`x_test`) and save it to the array `TreePredictions`.

In [ ]:
TreePredictions = Tree.predict(x_test)

print (predicitions [0:5])
print (y_test [0:5])

[0. 0. 1. 0. 0.]
3066    0.0
2456    0.0
1629    1.0
838     1.0
2506    0.0
Name: RainTomorrow, dtype: float64


#### Q11) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.

In [ ]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score

predictions_binary = (TreePredictions >= 0.5).astype(int)
Tree_Accuracy_Score = accuracy_score(y_test, predictions_binary)
Tree_JaccardIndex = jaccard_score(y_test, predictions_binary)
Tree_F1_Score = f1_score(y_test, predictions_binary)

print(f"KNN Accuracy Score: {Tree_Accuracy_Score}")
print(f"KNN Jaccard Index: {Tree_JaccardIndex}")
print(f"KNN F1 Score: {Tree_F1_Score}")

KNN Accuracy Score: 0.8183206106870229
KNN Jaccard Index: 0.48034934497816595
KNN F1 Score: 0.6489675516224189


# Logistic Regression

#### Q12) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `1`.

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

#### Q13) Create and train a LogisticRegression model called LR using the training data (`x_train`, `y_train`) with the `solver` parameter set to `liblinear`.

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

# Create a LogisticRegression model
LR = LogisticRegression(solver='liblinear')

# Define the parameter grid for C
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100]}

# Use GridSearchCV to find the best C value
grid_search = GridSearchCV(estimator=LR, param_grid=param_grid, cv=5)  # 5-fold cross-validation
grid_search.fit(x_train, y_train)

# Get the best C value
best_C = grid_search.best_params_['C']
print(f"The best C value is: {best_C}")

The best C value is: 0.001


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

LR = LogisticRegression(C=0.001, solver='liblinear').fit(x_train,y_train)
LR

LogisticRegression(C=0.001, solver='liblinear')

#### Q14) Now, use the `predict` and `predict_proba` methods on the testing data (`x_test`) and save it as 2 arrays `predictions` and `predict_proba`.

In [ ]:
predictions = LR.predict(x_test)

predictions

array([0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 1., 0.

In [ ]:
predict_proba = LR.predict_proba(x_test)

predict_proba

array([[0.68601258, 0.31398742],
       [0.97205222, 0.02794778],
       [0.46999258, 0.53000742],
       ...,
       [0.96089074, 0.03910926],
       [0.77657571, 0.22342429],
       [0.45272128, 0.54727872]])

#### Q15) Using the `predictions`, `predict_proba` and the `y_test` dataframe calculate the value for each metric using the appropriate function.

In [ ]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score, log_loss

predictions = LR.predict(x_test)
predict_proba = LR.predict_proba(x_test)

LR_Accuracy_Score = accuracy_score(y_test, predictions)
LR_JaccardIndex = jaccard_score(y_test, predictions)
LR_F1_Score = f1_score(y_test, predictions)
LR_Log_Loss = log_loss(y_test, predictions)

print("Accuracy Score: ", LR_Accuracy_Score)
print("Jaccard Index: ", LR_JaccardIndex)
print("F1 Score: ", LR_F1_Score)
print("Log Loss: ", LR_Log_Loss)

Accuracy Score:  0.8213740458015267
Jaccard Index:  0.4583333333333333
F1 Score:  0.6285714285714286
Log Loss:  6.438331979430086


#SVM

#### Q16) Create and train a SVM model called SVM using the training data (`x_train`, `y_train`).

In [ ]:
from sklearn import svm
SVM = svm.SVC(kernel = 'rbf')
SVM.fit(x_train, y_train)

SVC()

#### Q17) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.

In [ ]:
predictions = SVM.predict(x_test)
predictions [0:5]

array([0., 0., 0., 0., 0.])

#### Q18) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.

In [ ]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score

SVM_Accuracy_Score = accuracy_score(y_test, predictions)
SVM_JaccardIndex = jaccard_score(y_test, predictions)
SVM_F1_Score = f1_score(y_test, predictions)

print("Accuracy Score: ", SVM_Accuracy_Score)
print("Jaccard Index: ", SVM_JaccardIndex)
print("F1 Score: ", SVM_F1_Score)

Accuracy Score:  0.7221374045801526
Jaccard Index:  0.0
F1 Score:  0.0


#### Q19) Show the Accuracy,Jaccard Index,F1-Score and LogLoss in a tabular format using data frame for all of the above models.

\*LogLoss is only for Logistic Regression Model


In [ ]:
import pandas as pd

metrics = {
    'Model': ['Logistic Regression', 'Decision Tree', 'SVM', 'KNN'],
    'Accuracy': [0.82, 0.82, 0.72, 0.84],
    'Jaccard Index': [0.46, 0.48, 0, 0.51],
    'F1-Score': [0.63, 0.64, 0.0, 0.68],
    'Log Loss': [6.43, '-' , '-', '-']
}

df = pd.DataFrame(metrics)
df

Model  Accuracy  Jaccard Index  F1-Score Log Loss
0  Logistic Regression      0.82           0.46      0.63     6.43
1        Decision Tree      0.82           0.48      0.64        -
2                  SVM      0.72           0.00      0.00        -
3                  KNN      0.84           0.51      0.68        -

#Key Observations

<b>Accuracy:</b>
KNN has the highest accuracy at 0.84, followed by Logistic Regression and Decision Tree at 0.82.
SVM lags significantly at 0.72.

<b>Jaccard Index:</b>
KNN again performs best with 0.51, slightly better than Decision Tree (0.48) and Logistic Regression (0.46).
SVM has a value of 0.00, indicating it fails to predict positive instances correctly.

<b>F1-Score:</b>
KNN leads with 0.68, followed by Decision Tree (0.64) and Logistic Regression (0.63).
SVM performs poorly with 0.00.

<b>Log Loss:</b>
Only Logistic Regression has a Log Loss value, and 6.43 indicates significant uncertainty in its predictions.
Decision Tree and KNN do not provide Log Loss in this case, so the comparison is incomplete for this metric.
Best Model: KNN
KNN outperforms the others in Accuracy, Jaccard Index, and F1-Score, making it the best overall choice based on the available metrics.
Logistic Regression has a comparable performance but is slightly less robust than KNN.